import full_BalanceVault from "./BalanceVault.json";
import full_BalancerVault from "./BalancerVault.json";
import full_BalancerWeightedPool from "./BalancerWeightedPool.json";
import full_BondCalcContract from "./BondCalcContract.json";
import full_BondContract from "./BondContract.json";
import full_BondStakingDepository from "./BondStakingDepository.json";
import full_BridgeConverter from "./BridgeConverter.json";
import full_CirculatingSupplyContract from "./CirculatingSupplyContract.json";
import full_Cryptopunks from "./cryptopunks.json";
import full_DistributorContract from "./DistributorContract.json";
import full_ERC1155 from "./ERC1155.json";
import full_ERC165 from "./ERC165.json";
import full_ExpandedIERC20 from "./ExpandedIERC20.json";
import full_FHUDContract from "./FHUDContract.json";
import full_Factory from "./Factory.json";
import full_FuseProxy from "./FuseProxy.json";
import full_IERC20 from "./IERC20.json";
import full_IERC721 from "./IERC721.json";
import full_LPStaking from "./LPStaking.json";
import full_LpBondCalcContract from "./LpBondCalcContract.json";
import full_Lqdr from "./Lqdr.json";
import full_LqdrUsdbPolBondDepository from "./LqdrUsdbPolBondDepository.json";
import full_MasterChefAbi from "./MasterChefAbi.json";
import full_MasterChefBeets from "./MasterChefBeets.json";
import full_MasterChefLqdr from "./MasterChefLqdr.json";
import full_MigrateToOHM from "./MigrateToOHM.json";
import full_Multicall from "./Multicall.json";
import full_OHMPreSale from "./OHMPreSale.json";
import full_OhmLusdCrucible from "./OhmLusdCrucible.json";
import full_OlympusStaking from "./OlympusStaking.json";
import full_OlympusStakingv2 from "./OlympusStakingv2.json";
import full_PairContract from "./PairContract.json";
import full_Potion from "./Potion.json";
import full_RedeemHelper from "./RedeemHelper.json";
import full_StablePool from "./StablePool.json";
import full_StakingHelper from "./StakingHelper.json";
import full_Synthetic from "./Synthetic.json";
import full_TShareRewardPool from "./TShareRewardPool.json";
import full_TombMasonry from "./TombMasonry.json";
import full_USDBContract from "./USDBContract.json";
import full_USDBMinter from "./USDBMinter.json";
import full_USDBNft from "./USDBNft.json";
import full_UniswapIERC20 from "./UniswapIERC20.json";
import full_UniswapV2Pair from "./UniswapV2Pair.json";
import full_gohm from "./gohm.json";
import full_mimirTokenSale from "./mimirTokenSale.json";
import full_mwsFHM from "./mwsFHM.json";
import full_pOlyTokenSale from "./pOlyTokenSale.json";
import full_sOHM from "./sOHM.json";
import full_sOhmv2 from "./sOhmv2.json";
import full_wMEMO from "./wMEMO.json";
import full_wsOHM from "./wsOHM.json";
import full_xFhm from "./xFhm.json";
import full_BalanceVaultManager from "./BalanceVaultManager.json";

// reserves
import full_DAIContract from "./reserves/DAIContract.json";
import full_OhmDai from "./reserves/OhmDai.json";
import full_OhmEth from "./reserves/OhmEth.json";
import full_OhmFrax from "./reserves/OhmFrax.json";
import full_OhmLusd from "./reserves/OhmLusd.json";

// 33-together
import full_AwardAbi from "./33-together/AwardAbi.json";
import full_AwardAbi2 from "./33-together/AwardAbi2.json";
import full_PrizePoolAbi from "./33-together/PrizePoolAbi.json";
import full_PrizePoolAbi2 from "./33-together/PrizePoolAbi2.json";

// bonds
import full_BondDepository from "./bonds/BondDepository.json";
import full_BondsBondStakingDepository from "./bonds/BondStakingDepository.json";
import full_FhudABondDepository from "./bonds/FhudABondDepository.json";
import full_FhudBBondDepository from "./bonds/FhudBBondDepository.json";
import full_SingleSidedLPBondDepository from "./bonds/SingleSidedLPBondDepository.json";
import full_TradFiBondDepository from "./bonds/TradFiBondDepository.json";
import full_UsdbFhmBurnBondDepository from "./bonds/UsdbFhmBurnBondDepository.json";
import full_UsdbABondDepository from "./bonds/UsdbABondDepository.json";
import full_UsdbNftBondDepository from "./bonds/UsdbNftBondDepository.json";

//nft-lending
import full_UsdbLending from "./UsdbLending.json";
import merkle_distributor from "./BalanceMerkleDistributor.json";
import full_StakingBackedNFTPool from "./StakingBackedNFTPool.json";
import full_AmpsToken from "./AmpsToken.json";

//passNFT-mint
import full_PassNFT from "./passNFT.json";

export const balanceVaultAbi = full_BalanceVault.abi;
export const balancerVaultAbi = full_BalancerVault.abi;
export const balancerWeightedPoolAbi = full_BalancerWeightedPool.abi;
export const bondCalcContractAbi = full_BondCalcContract.abi;
export const bondContractAbi = full_BondContract.abi;
export const bondStakingDepositoryAbi = full_BondStakingDepository.abi;
export const bridgeConverterAbi = full_BridgeConverter.abi;
export const circulatingSupplyContractAbi = full_CirculatingSupplyContract.abi;
export const cryptopunksAbi = full_Cryptopunks.abi;
export const distributorContractAbi = full_DistributorContract.abi;
export const erc1155Abi = full_ERC1155.abi;
export const erc165Abi = full_ERC165.abi;
export const expandedIERC20Abi = full_ExpandedIERC20.abi;
export const fhudContractAbi = full_FHUDContract.abi;
export const factoryAbi = full_Factory.abi;
export const fuseProxyAbi = full_FuseProxy.abi;
export const ierc20Abi = full_IERC20.abi;
export const ierc721Abi = full_IERC721.abi;
export const lpStakingAbi = full_LPStaking.abi;
export const lpBondCalcContractAbi = full_LpBondCalcContract.abi;
export const lqdrAbi = full_Lqdr.abi;
export const lqdrUsdbPolBondDepositoryAbi = full_LqdrUsdbPolBondDepository.abi;
export const masterChefAbi = full_MasterChefAbi.abi;
export const masterChefBeetsAbi = full_MasterChefBeets.abi;
export const masterChefLqdrAbi = full_MasterChefLqdr.abi;
export const migrateToOHMAbi = full_MigrateToOHM.abi;
export const multicallAbi = full_Multicall.abi;
export const ohmPreSaleAbi = full_OHMPreSale.abi;
export const ohmLusdCrucibleAbi = full_OhmLusdCrucible.abi;
export const olympusStakingAbi = full_OlympusStaking.abi;
export const olympusStakingv2Abi = full_OlympusStakingv2.abi;
export const pairContractAbi = full_PairContract.abi;
export const potionAbi = full_Potion.abi;
export const redeemHelperAbi = full_RedeemHelper.abi;
export const stablePoolAbi = full_StablePool.abi;
export const stakingHelperAbi = full_StakingHelper.abi;
export const syntheticAbi = full_Synthetic.abi;
export const tShareRewardPoolAbi = full_TShareRewardPool.abi;
export const tombMasonryAbi = full_TombMasonry.abi;
export const usdbContractAbi = full_USDBContract.abi;
export const usdbMinterAbi = full_USDBMinter.abi;
export const usdbNftAbi = full_USDBNft.abi;
export const uniswapIERC20Abi = full_UniswapIERC20.abi;
export const uniswapV2PairAbi = full_UniswapV2Pair.abi;
export const gohmAbi = full_gohm.abi;
export const mimirTokenSaleAbi = full_mimirTokenSale.abi;
export const mwsFHMAbi = full_mwsFHM.abi;
export const polyTokenSaleAbi = full_pOlyTokenSale.abi;
export const sOhmAbi = full_sOHM.abi;
export const sOhmv2Abi = full_sOhmv2.abi;
export const wMemoAbi = full_wMEMO.abi;
export const wsOhmAbi = full_wsOHM.abi;
export const xFhmAbi = full_xFhm.abi;
export const balanceVaultManager = full_BalanceVaultManager.abi;
export const daiContractAbi = full_DAIContract.abi;
export const ohmDaiAbi = full_OhmDai.abi;
export const ohmEthAbi = full_OhmEth.abi;
export const ohmFraxAbi = full_OhmFrax.abi;
export const ohmLusdAbi = full_OhmLusd.abi;
export const awardAbi = full_AwardAbi.abi;
export const award2Abi = full_AwardAbi2.abi;
export const prizePoolAbi = full_PrizePoolAbi.abi;
export const prizePool2Abi = full_PrizePoolAbi2.abi;
export const bondDepositoryAbi = full_BondDepository.abi;
export const bondsBondStakingDepositoryAbi = full_BondsBondStakingDepository.abi;
export const fhudABondDepositoryAbi = full_FhudABondDepository.abi;
export const fhudBBondDepositoryAbi = full_FhudBBondDepository.abi;
export const singleSidedLPBondDepositoryAbi = full_SingleSidedLPBondDepository.abi;
export const tradFiBondDepositoryAbi = full_TradFiBondDepository.abi;
export const usdbFhmBurnBondDepositoryAbi = full_UsdbFhmBurnBondDepository.abi;
export const usdbABondDepositoryAbi = full_UsdbABondDepository.abi;
export const usdbNftBondDepositoryAbi = full_UsdbNftBondDepository.abi;
export const passNFTAbi = full_PassNFT.abi;

//nft-lending
export const usdbLending = full_UsdbLending.abi;
export const merkleDistributor = merkle_distributor;
export const stakingBackedNFTPool = full_StakingBackedNFTPool.abi;
export const ampsToken = full_AmpsToken.abi;
